# Generated by Django 5.0.3 on 2024-05-11 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProdutoNome',
            fields=[
                ('Nome', models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='Nome')),
            ],
        ),
    ]
