# Generated by Django 4.2.13 on 2024-05-16 21:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_lote_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lote',
            name='Nome',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='nome_lote', to='core.produtonome'),
        ),
    ]
