# Generated by Django 4.2.13 on 2024-05-20 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_lote_nome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lote',
            name='Nome',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Nome'),
        ),
    ]
