# Generated by Django 4.2.13 on 2024-10-10 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_lote_nome'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
                ('Emailforn', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('Nome', models.CharField(max_length=100, verbose_name='Nome')),
            ],
        ),
        migrations.AddField(
            model_name='produtonome',
            name='Formail',
            field=models.ManyToManyField(blank=True, null=True, related_name='produtos324', to='core.fornecedor'),
        ),
    ]
