# Generated by Django 4.2.13 on 2024-10-29 00:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_fornecedor_produtonome_formail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produtonome',
            name='Formail',
        ),
    ]
