# Generated by Django 4.2.13 on 2024-10-29 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_produtonome_formail'),
    ]

    operations = [
        migrations.AddField(
            model_name='produtonome',
            name='Formail1',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email1'),
        ),
        migrations.AddField(
            model_name='produtonome',
            name='Formail2',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email2'),
        ),
        migrations.AddField(
            model_name='produtonome',
            name='Formail3',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email3'),
        ),
        migrations.AddField(
            model_name='produtonome',
            name='Formail4',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email4'),
        ),
        migrations.AddField(
            model_name='produtonome',
            name='Formail5',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email5'),
        ),
    ]
