# Generated by Django 4.2.13 on 2025-10-04 00:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_produtonome_formail1_produtonome_formail2_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovProd',
            fields=[
                ('Id', models.UUIDField(primary_key=True, serialize=False)),
                ('Tipo', models.CharField(choices=[('entrada', 'Entrada'), ('saida', 'Saída')], max_length=10)),
                ('Data', models.DateField()),
                ('Quantidade', models.PositiveBigIntegerField(default=0)),
                ('Produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.produtonome')),
            ],
        ),
    ]
