# Generated by Django 4.2.13 on 2025-10-04 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_movprod'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movprod',
            name='Id',
        ),
        migrations.AddField(
            model_name='movprod',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
